name: "[TEMPLATE] CD: Github Artifact"

on:
  workflow_call:
    inputs:
      service-name:
        description: "Name of the service (e.g., factset-mcp)"
        required: true
        type: string
      service-tag:
        description: "Github release tag of the package (e.g., factset-mcp@1.2.0)"
        required: true
        type: string

jobs:
  # Builds and upload the built code artifact to the Github release
  github-artifact:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      NPM_PACKAGE_NAME: '@unscoped/${{ inputs.service-name }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --filter=${{ env.NPM_PACKAGE_NAME }}

      - name: Build package
        run: pnpm build --filter=${{ env.NPM_PACKAGE_NAME }}

      - name: Pack package
        run: pnpm pack --filter=${{ env.NPM_PACKAGE_NAME }} --out=build.tgz

      - name: Upload build artifact
        run: gh release upload ${{ inputs.service-tag }} build.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

